#' Data Generating Process
#'
#' Generates observations from the specified model with
#' hyperbolic secant distributed innovations.
#'
#' @param spec specification object create by `SLSAGARCH2::specification`
#' @param param true parameters of the DGP
#' @param n sample size
#' @param R number of Monte Carlo replications
#' @param seed the seed for the rng
#' @param burn.in the burnin period
#' @param nthreads number of threads to use for parallel simulation
#'
#' @return An n x R matrix of simulated observations.
#' @export
#' 
dgp <- function(spec, param, n, R, seed, burn.in = 25000L, nthreads = 4L, ...) {
  # Simulate the innovations
  z <- matrix(data = SLSAGARCH2::rdist(
    dist = spec$distribution, n = R * (n + burn.in), ...), ncol = R)

  # Extract the parameters
  theta <- SLSAGARCH2:::expand_par(spec = spec, x = param)

  # Pass the innovations to simulate
  res <- switch(
    spec$type,
    "a" = SLSAGARCH2:::lstParallelGenerate(
      Z = z, param = theta, model = 0L,
      dist = spec$dist_id, nthreads = nthreads),
    "s" = SLSAGARCH2:::lstParallelGenerate(
      Z = z, param = theta, model = 1L,
      dist = spec$dist_id, nthreads = nthreads)
  )

  # Extract the data
  res$y[-1 * 1:burn.in, ]
}

#' Fit Specified Model to Simulated Data
#'
#' This is a simple wrapper around `SLSAGARCH2::estimate` that
#' produces a tibble suitably for further analysis.
#'
#' @param spec specification object create by `SLSAGARCH2::specification`
#' @param param true parameters of the DGP
#' @param y simulated observations
#' @param se_type method for calculating the standard errors
#' @param ... additional arguments passed to `SLSAGARCH2::estimate`
#'
#' @return A tibble with estimates
#' @export
#'
#' @examples
#' 
fit <- function(spec, param, y, se_type = "QMLE", ...) {
  status <- rep(-1, spec$k)
  elapsed <- parhat <- se <- rep(NA, spec$k)

  try(expr = {
    # Estimate the model
    est_model <- SLSAGARCH2::estimate(spec, x = y, ...)

    # Status
    status <- rep(est_model$status, spec$k)
    elapsed <- rep(est_model$elapsed, spec$k)

    # Extract the coefficients and standard errors
    parhat <- SLSAGARCH2:::coef.fitted(est_model)
    se <- SLSAGARCH2:::vcov.fitted(est_model, type = se_type) |>
      diag() |>
      sqrt()
  })

  # Create the data frame
  dplyr::tibble(
    status = status, par = spec$names,
    true = as.vector(unlist(param)), est = parhat, se = se,
    elapsed = elapsed) |>
    dplyr::filter(par != "h0")
}

#' Fit Many
#'
#' @param spec specification object create by `SLSAGARCH2::specification`
#' @param param true parameters of the DGP
#' @param ymat matrix of simulated observations
#' @param se_type method for calculating the standard errors
#' @param label a label used to identify the simulation
#' @param strategy evaluation function (or name of it) to use for resolving a future. If NULL, then the current strategy is returned.
#' @param nchunks controls the number of realisations to pass to each thread
#' @param .errorhandling specifies how a task evaluation error should be handled. If the value is "stop", then execution will be stopped via the stop function if an error occurs. If the value is "remove", the result for that task will not be returned, or passed to the .combine function. If it is "pass", then the error object generated by task evaluation will be included with the rest of the results. It is assumed that the combine function (if specified) will be able to deal with the error object. The default value is "stop".
#' @param verbose logical flag enabling verbose messages
#' @param ...
#'
#' @return a dataframe
#'
#' @details
#' This function creates a `progressor` that signals progress updates. The user
#' can run the function inside of a `with_progress` function to show a progress
#' bar.
#'
#' @importFrom doFuture %dofuture%
#' @importFrom foreach foreach
#' @importFrom foreach %do%
#' @export
#'
#' @examples
#' 
fit_many <- function(spec, param, ymat, se_type = "QMLE",
                     label = sim_lab(
                       n = nrow(ymat), lambda = param["lambda"],
                       rho = param["rho"]),
                     strategy = "sequential", nchunks = 100,
                     .errorhandling = "remove", verbose = FALSE, ...) {
  if (!is.null(strategy)) {
    switch(strategy,
           "sequential" = future::plan(strategy = future::sequential),
           "multisession" = future::plan(strategy = future::multisession),
           "multicore" = future::plan(strategy = future::multicore)
    )
  }
  chunks <- chunk(1:ncol(ymat), nchunks)
  p <- progressr::progressor(steps = length(chunks))
  p(amount = 0)
  out <- foreach::foreach(
    i = 1:nchunks, .combine = "rbind", .inorder = FALSE, .verbose = verbose,
    .options.future = list(seed = TRUE), .errorhandling = .errorhandling
  ) %dofuture% {
    idx <- chunks[[i]]
    ymat_i <- ymat[, idx]
    out_i <- foreach::foreach(
      j = 1:ncol(ymat_i), .combine = "rbind", .inorder = FALSE,
      .options.future = list(seed = TRUE)) %dofuture% {
        res <- fit(spec, param, ymat_i[, j], se_type, ...)
        res$sample <- idx[j]
        res$nobs <- nrow(ymat_i)
        res
      }
    p(message = sprintf("Completed chunk %d", i))
    out_i
  }
  cbind("Simulation" = label, out)
}
