# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate From a Hyperbolic Secant Distribution in Parallel
#'
#' Simulates `n` observations from `m` independent hyperbolic secant
#' distributed random variables.
#'
#' @param n Number of observations to generate each replication
#' @param m Number of replications
#' @param seed Seed for the rng
#' @param numThreads Number of threads for running code in parallel
#'
#' @details
#' IMPORTANT: `seed` works in cojunction with `numThreads`. Therefore,
#' setting `seed = 42` and `numThreads = 2` will produce differents 
#' results compared to setting `seed = 42` and `numThreads = 4`.
#' 
#' @name prhs
#' @export prhs
prhs <- function(n, m, seed, numThreads = -1L) {
    .Call(`_SimStudySLSAGARCH_prhs`, n, m, seed, numThreads)
}

