# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parallelRhs <- function(n, m, seed) {
    .Call(`_SimStudySLSAGARCH_parallelRhs`, n, m, seed)
}

rcpp_hello_world <- function() {
    .Call(`_SimStudySLSAGARCH_rcpp_hello_world`)
}

parallel_random_matrix <- function(n, m, ncores, seed) {
    .Call(`_SimStudySLSAGARCH_parallel_random_matrix`, n, m, ncores, seed)
}

